# --- Setup ---

self := "setup"
import "../prelude/task/justfile"
_default: help

# --- Tasks ---

# Install desired brew packages.
brew:
  #!/usr/bin/env bash
  set -euo pipefail

  # Bitwarden password manager.
  brew install --cask bitwarden

  # Arc browser.
  brew install --cask arc

  # Warp terminal.
  brew install --cask warp

  # Dock utility to manage macOS dock items.
  # - https://formulae.brew.sh/formula/dockutil
  # - https://github.com/kcrawford/dockutil
  brew install dockutil

# Manual steps needed for arc.
arc:
  #!/usr/bin/env bash
  set -euo pipefail

  # Action items.
  # - [ ] Login.
  # - [ ] Settings -> Kyle -> Sync sidebar.
  # - [ ] Settings -> Profiles -> Make: Personal, Stoke, Ragkit.
  # - [ ] Settings -> Profiles -> Set as Default
  # - [ ] Settings -> Profiles -> Archive Tabs after 30 days
  # - [ ] Settings -> Profiles -> Downloads -> Ask Every Time
  # - [ ] Settings -> Arc -> Set as Default Browser
  # - [ ] On Each Profile -> Passwords -> Settings -> Disable Offer to Save Passwords

# Configures the mac dock.
mac-dock:
  #!/usr/bin/env bash
  set -euo pipefail

  # TODO: Check that dockutil is installed. Say to use brew install if not.
  DOCK_ITEMS=$(dockutil --list | awk -F'file:///' '{gsub(/[[:space:]]+$/, "", $1); print $1}')

  try_remove_dock_item() {
    if echo "$DOCK_ITEMS" | grep -Fxq "$1"; then
      dockutil --remove "$1" --no-restart
    fi
  }

  # Keep: Finder, System Settings, Downloads, Trash.
  try_remove_dock_item "Launchpad"
  try_remove_dock_item "Messages"
  try_remove_dock_item "Safari"
  try_remove_dock_item "Mail"
  try_remove_dock_item "Maps"
  try_remove_dock_item "Photos"
  try_remove_dock_item "FaceTime"
  try_remove_dock_item "Calendar"
  try_remove_dock_item "Contacts"
  try_remove_dock_item "Reminders"
  try_remove_dock_item "Notes"
  try_remove_dock_item "Freeform"
  try_remove_dock_item "TV"
  try_remove_dock_item "Music"
  try_remove_dock_item "News"
  try_remove_dock_item "Keynote"
  try_remove_dock_item "Numbers"
  try_remove_dock_item "Pages"
  try_remove_dock_item "App Store"

  # Finally, remove spacer tiles and do a restart.
  dockutil --remove spacer-tiles --restart

mac-defaults:
  #!/usr/bin/env bash
  set -euo pipefail

  # Check if we are on macOS.
