# --- Setup ---

self := "install"
import "../prelude/task/justfile"
_default: help

# --- Tasks ---

# Install desired brew packages.
brew:
  #!/usr/bin/env bash

  set -euo pipefail

  # Bitwarden password manager.
  brew install --cask bitwarden

  # Arc browser.
  brew install --cask arc

  # Warp terminal.
  brew install --cask warp
