# --- Setup ---

self := "bootstrap"
import "../prelude/task/justfile"
_default: help

# --- Tasks ---

# Generates environment variables for the 'kyldvs' command.
shellenv *args:
  #!/usr/bin/env bash
  set -euo pipefail

  cat <<EOS
export PATH="${KYLDVS_BIN}:\${PATH}"
export KYLDVS_PREFIX="${KYLDVS_PREFIX}"
export KYLDVS_REPOSITORY="${KYLDVS_REPOSITORY}"
EOS

# Pulls the latest changes to 'kyldvs' from github.
sync *args:
  #!/usr/bin/env bash
  set -euo pipefail

  echo "Syncing ${KYLDVS_REPOSITORY} with latest changes..."
  git -C "${KYLDVS_REPOSITORY}" pull origin main
